server:
    port: 8080

spring:
    profiles:
        active: dev
        include:
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    jackson:
        serialization.indent_output: true