server:
  compression:
    enabled: true
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
    url: jdbc:h2:mem:devdb
    username: sa
    password: sa
    serverName:
    platform: hsql
    driverClassName: org.h2.Driver
    continue-on-error: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    time-zone: UTC
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      hikari:
        minimumIdle: 10
        maximumPoolSize: 300
        idleTimeout: 300000
        maxLifetime: 600000
        connectionTestQuery: select count(*) from users
    properties:
      hibernate.id.new_generator_mappings: true
      #hibernate.cache.use_second_level_cache: true
      #hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.hbm2ddl.import_files: import.sql
      javax.persistence.validation.mode: NONE

app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

