INSERT INTO roles(name) VALUES('ROLE_USER');
INSERT INTO roles(name) VALUES('ROLE_ADMIN');
INSERT INTO USERS(ID,CREATED_AT,CREATE_USER,DATA_STATUS,DELETED_AT,UPDATE_USER,UPDATED_AT,VERSION,EMAIL,NAME,PASSWORD,USERNAME)VALUES (1,now(),null,'ACTIVE',null,null,null,1,'merchant@test.com','benan','$2a$10$pTJnv0HdyjIH7NSqcHiJEu.U7Q44SrW7SHI5FuUfjPaqgPOIIiO2G','benan')